### PR TITLE
Filament v3 support

### PR DESCRIPTION
**Pull request by saulens22**
This pull request adds support for Filament v3.

There's no notable changes in v3 that might prevent this package working on v2 also (as far as I know).

Also adding `.gitignore` / removing `composer.lock` from repository for better development :)

### CODE REVIEW

**Comment by saulens22** [comment]
After some more digging I've found that `when()` method was changed between versions. Now it doesn't resolve `$get()` parameter. I'll try fixing it soon.

**Comment by ziming** [comment]
@saulens22 If you look at the upgrade guide in the official docs it says this

https://filamentphp.com/docs/3.x/panels/upgrade-guide#get-and-set-closure-parameters

> In the forms package, $get and $set parameters now use a type of either \Filament\Forms\Get or \Filament\Forms\Set instead of \Closure. This allows for better IDE autocomplete support of the parameters of each function.
> 
> An easy way to upgrade your code quickly is to find and replace:
> 
> Closure $get to \Filament\Forms\Get $get
> Closure $set to \Filament\Forms\Set $set

**Comment by saulens22** [comment]
Using `when` on components would use function from here: https://github.com/illuminate/conditionable/blob/master/Traits/Conditionable.php

It doesn't inject `Get $get`.  So I've switched to `visible` instead, I hope it's OK.

Also, using `Get $get` requires Filament v3, so that's a breaking change.

**Comment by howdu** [comment]
@dmandrade I've been testing this PR on v3 for a few days now and it's working well.

**Comment by dmandrade** [comment]
Thanks @saulens22 !

**Pull request merged**
